version: '3.6'

services:
  owncast:
    image: gabekangas/owncast:latest
    container_name: owncast
    hostname: owncast
    restart: 'always'
    volumes:
      - data:/app
    ports:
      - 8080:8080/tcp
      - 1935:1935/tcp
    networks:
      - frontend

volumes:
  data:
    driver: local

networks:
  frontend:
    driver: bridge