version: '3.6'

services:
  owncast:
    image: gabekangas/owncast:latest
    container_name: owncast
    hostname: owncast
    restart: 'always'
    volumes:
      - type: bind
        source: ./data
        target: /data/config
    ports:
      - 8080:8080/tcp
      - 1935:1935/tcp